# Site settings
title: Imagine Jekyll
email: brian.lxchen@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Jekyll theme based on Imagine Bootstrap Template under CC BY 3.0 license, 
  which means footer credits must remain in place.
  The original source code can be found on colorlib.
# baseurl: "" # the subpath of your site, e.g. /blog
url: https://icheft.github.io/imagine-jekyll # the base hostname & protocol for your site, e.g. http://example.com
github_username:  icheft

# Build settings
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
